name: mlayout
version: '0.0.1'
synopsis: Compiler for memory layout descriptions
description: An executable that parses a DSL and generates code to access structured memory for different languages
category: Development
author: Aleksey Makarov
maintainer: aleksey.makarov@gmail.com
copyright: Aleksey Makarov
license: BSD3
homepage: https://github.com/aleksey-makarov/mlayout
dependencies:
  - base
tested-with: GHC == 8.10.7
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wno-redundant-constraints
extra-doc-files:
    - ChangeLog.md
    - README.md

github: aleksey-makarov/mlayout

library:
  source-dirs: src
  dependencies:
    - formatting
    - parsers
    - prettyprinter
    - text
    - trifecta
    - unordered-containers
  exposed-modules:
    - MLayout.Parser
    - MLayout.Data

# https://github.com/haskell/cabal/issues/7577
tests:
  tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - mlayout
      - directory
      - filepath
      - prettyprinter
      - tasty
      - tasty-golden
      - text
      - trifecta
      - unix

executables:
  mlayout:
    main: MLayout.hs
    source-dirs: app
    ghc-options: -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - mlayout
      - optparse-applicative
      - prettyprinter
      - prettyprinter-compat-ansi-wl-pprint
      - text
      - trifecta
